name: Deploy Graph to Staging

on:
  push:
    branches: [staging]

jobs:
  deploy-mainnet:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: "balancer-gauges-beta"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.yaml"
  deploy-goerli:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: "balancer-gauges-goerli-beta"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.goerli.yaml"
  deploy-arbitrum:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: "balancer-gauges-arbitrum-beta"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.arbitrum.yaml"
  deploy-polygon:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: "balancer-gauges-polygon-beta"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.polygon.yaml"
  deploy-optimism:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: "balancer-gauges-optimism-beta"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.optimism.yaml"
  deploy-gnosis:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: "balancer-gauges-gnosis-chain-b"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.gnosis.yaml"
  deploy-avalanche:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: "balancer-gauges-avalanche-beta"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.avalanche.yaml"
